apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt/vendir/vsphere_cpi/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: 0fa3055c5cddf67f8c23edea420575cb4eb7d5d8
    includePaths:
    - addons/packages/vsphere-cpi/1.22.5/bundle/config/**/*
- path: ytt/vendir/cni/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: f0774ead4e7f39dcb83e82444dd7f046d42b2dd6
    includePaths:
    - addons/packages/antrea/1.5.3/bundle/config/**/*
    - addons/packages/calico/3.22.1/bundle/config/**/*
- path: ytt/vendir/kapp-controller/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: 9d01646e433d40356c58279a06ea61567049f2de
    includePaths:
    - addons/packages/kapp-controller/0.41.2/bundle/config/**/*
